# Generated by Django 4.2.1 on 2023-05-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_subscriptionplans"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscriptionPlans",
            new_name="SubscriptionPlan",
        ),
    ]
