# Generated by Django 4.2.1 on 2023-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_id", models.CharField()),
                ("access_token", models.CharField()),
                ("refresh_token", models.CharField()),
                ("expiry_date", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="slug",
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name="club",
            name="merchant_access_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.merchant"
            ),
        ),
    ]
