# Generated by Django 4.2.1 on 2023-05-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_subscriptionplans_subscriptionplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="uid",
            new_name="subscription_id",
        ),
    ]
