# Generated by Django 4.2.1 on 2023-05-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_merchant_alter_club_name_alter_club_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="merchant_access_token",
            new_name="merchant",
        ),
    ]
