# Generated by Django 4.2.1 on 2023-05-21 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_merchant_access_token_club_merchant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="merchant",
        ),
        migrations.AddField(
            model_name="user",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
