# Generated by Django 4.2.1 on 2023-05-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_club_merchant_user_merchant_alter_club_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="subscription_id",
            new_name="catalog_item_id",
        ),
        migrations.AddField(
            model_name="merchant",
            name="currency",
            field=models.CharField(default="USD", max_length=5),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.club"
            ),
        ),
    ]
