# Generated by Django 4.2.1 on 2023-05-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_subscriptionplan_description_subscriptionplan_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
